---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Get python version
        run: sed -n "s/^FROM \(.*\/\)\?python:\([0-9\.]\+\).*/\2/p" web/Dockerfile > .python-version
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version-file: ".python-version"
      - name: Install python dependencies
        run: pip3 install -c web/requirements-dev.txt ruff yamllint
      - name: Run yamllint
        run: |
          yamllint -s -d '{extends: default, rules: {line-length: disable}}' .
      - name: Run ruff check
        run: ruff check
      - name: Run ruff format
        run: ruff format --check
